### ISSUE TITLE
programs API with filter_started_at_lt returns incorrect programs

### ISSUE THREAD

**Issue by pchw** [annict/annict#760] opened 2017-04-15 12:19 UTC
I requested the API using following params,

API: GET /v1/me/programs
```
{
  filter_unwatched: true,
  sort_started_at: "desc",
  page: 1,
  filter_started_at_lt: "2017/04/15 21:12"
}
```

API returned programs including `エロマンガ先生 #2 リア充委員長と不敵な妖精`.
the program will broadcast on `2017-04-16 00:30`. it should not be included.
![image](https://cloud.githubusercontent.com/assets/1183484/25063518/248b241e-2221-11e7-9e08-80d84eeae1ec.png)

**Comment by shimbaco** [comment] 2017-04-16 14:18
@pchw Hmm, that's strange... I'll look into it. Thank you for your issue!

**Comment by shimbaco** [comment] 2017-04-20 11:48
@pchw It might that you need to encode `"2017/04/15 21:12"`.
It seems to work when the date is added to URL directly like following.

```
$ curl -X GET https://api.annict.com/v1/me/programs?access_token=c38030dbff675f2b381cf2a31cb18d2763c8b0c35153b5ac378ca1eccfbaf271&sort_started_at=desc&filter_started_at_lt=2017/04/13%2021:12
```

**Comment by pchw** [comment] 2017-05-15 13:22
@shimbaco finally, i got why this issue happened.
```
http://api.annict.com/v1/me/programs?sort_started_at=desc&filter_started_at_lt="2017/05/15 15:31"&filter_unwatched=true&access_token=***
```
I requested above then i got following response
```
"id": 60571,
"started_at": "2017-05-15T15:30:00.000Z",
"is_rebroadcast": false,
"channel":{"id": 19, "name": "TOKYO MX"},
"work":{"id": 4986, "title": "ゼロから始める魔法の書", "title_kana": "ぜろからはじめるまほうのしょ", "media": "tv",…},
"episode":{"id": 91072, "number": "6", "number_text": "第6話", "sort_number": 60,…}
```
![image](https://cloud.githubusercontent.com/assets/1183484/26059417/b0405daa-39bc-11e7-94a3-d39f1c64b505.png)


`filter_started_at_lt` accepts TZ=0 datetime.
however I requested that `filter_started_at_lt` into JST datetime.

maybe this is specification.

**Comment by shimbaco** [comment] 2017-05-16 13:25
@pchw Ah, I see! Then this is by design. I updated the document to prevent a misunderstanding.
So I'll close this issue. Thank you for your report!

**Closed by shimbaco** 2017-05-16 13:25 UTC
